package com.eyemobile.payment;

import com.eyemobile.common.CardBrand;
import com.eyemobile.common.CardMode;
import com.eyemobile.common.PaymentProviderType;

import java.math.BigDecimal;
import java.util.List;

/**
 * Created by Tiago Felipe on 28/05/2018.
 *
 * <p/>
 * Description:<br>
 *  <strong>PaymentTransaction</strong>
 * <p/>
 *
 *  Attribute description:<br>
 *  <strong>paymentReference</strong> It's reference to uniquely identify some payment.<br>
 *  <strong>provider</strong> check the values in @link{@link PaymentProviderType}<br><br>
 *  <strong>cardBrand</strong> check the values in @link{@link CardBrand}<br><br>
 *  <strong>cardMode</strong> check the values in @link{@link CardMode}<br><br>
 *  <strong>metadata</strong> It holds the json generated by paymentProvider<br>
 */

public class PaymentTransaction {
    private String id;
    private String paymentReference;
    private PaymentProviderType provider;
    private String cardNumber;
    private String cardHolderName;
    private CardBrand cardBrand;
    private CardMode cardMode;
    private BigDecimal total;
    private List<Split> splits;
    private String time;
    private String metadata;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getPaymentReference() {
        return paymentReference;
    }

    public void setPaymentReference(String paymentReference) {
        this.paymentReference = paymentReference;
    }

    public PaymentProviderType getProvider() {
        return provider;
    }

    public void setProvider(PaymentProviderType provider) {
        this.provider = provider;
    }

    public String getCardNumber() {
        return cardNumber;
    }

    public void setCardNumber(String cardNumber) {
        this.cardNumber = cardNumber;
    }

    public String getCardHolderName() {
        return cardHolderName;
    }

    public void setCardHolderName(String cardHolderName) {
        this.cardHolderName = cardHolderName;
    }

    public CardBrand getCardBrand() {
        return cardBrand;
    }

    public void setCardBrand(CardBrand cardBrand) {
        this.cardBrand = cardBrand;
    }

    public CardMode getCardMode() {
        return cardMode;
    }

    public void setCardMode(CardMode cardMode) {
        this.cardMode = cardMode;
    }

    public BigDecimal getTotal() {
        return total;
    }

    public void setTotal(BigDecimal total) {
        this.total = total;
    }

    public List<Split> getSplits() {
        return splits;
    }

    public void setSplits(List<Split> splits) {
        this.splits = splits;
    }

    public String getTime() {
        return time;
    }

    public void setTime(String time) {
        this.time = time;
    }

    public String getMetadata() {
        return metadata;
    }

    public void setMetadata(String metadata) {
        this.metadata = metadata;
    }
}
